apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-ner-ru
  labels:
    app.kubernetes.io/name: service-ner-ru
    app.kubernetes.io/component: web
  namespace: rabbits
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: service-ner-ru
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-ner-ru
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: service-ner-ru
          image: artem1sobolev/service-ner-ru:1.0.3
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: rabbitmq
            - secretRef:
                name: rabbitmq-creds

